### ISSUE TITLE
老哥🐮🍺 从你的csdn博客来的，终于解决我的问题，不过刚才下了你的demo看了看，有个bug你没改过来

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [Coursem/FixFragmentNavigatorDemo#1]
![image](https://user-images.githubusercontent.com/54784104/147062714-9ee84c40-8df5-434f-b9c0-8465ef57bbc8.png)
就是这个了，你是在代码里定义的navGraph，xml里重复定义了会每次切换选项卡执行两次操作  

还有个人感觉在代码里写navigation配置太乱了，我是在xml中自定义了navGraph，然后将自定义的FragmentNavigator的@Navigator.Name注解用做fragment标签，重写了NavHostFragment替代NavHost默认的实现类，然后在bottomNavigationView.setOnItemSelectedListener的回调里做导航操作，借鉴了另一位老哥的[自定义FragmentNavigator和NavHostFragment](https://github.com/hegaojian/JetpackMvvm/tree/master/JetpackMvvm/src/main/java/me/hgj/jetpackmvvm/navigation)  

你这个切换页面只走onHideChange回调，这个老哥给改到了和普通的fragment走一样的生命周期，感觉更方便了😉

**Comment by Coursem** [comment]
好的  我在改一下  感谢老哥的的链接

**Comment by SaltedFish-Extreme** [comment]
> 好的 我在改一下 感谢老哥的的链接

老哥才是客气了，你的头像和我的一样，我一开始都没分清😂
